name: Build Geode Mod

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
          target: Win64
        - name: Android 32-bit
          os: ubuntu-latest
          target: Android32
        - name: Android 64-bit
          os: ubuntu-latest
          target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build with Geode SDK
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings: geode-sdk/bindings
          bindings-ref: main
          target: ${{ matrix.config.target }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: geode-mod-${{ matrix.config.target }}
          path: ${{ steps.build.outputs.build-output }}
